AWSTemplateFormatVersion: 2010-09-09

Description: AWS Perspective ElasticsearchDomain Stack

Parameters:

  AppName:
    Description:
      Please specify the Application Name. Used for tagging and resource
      names. Mandatory LOWER CASE.
    Type: String

  PerspectiveVpcCidr:
    Description: VPC CIDR
    Type: String
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'

  PrivateSubnet0:
    Description: Private Subnet 0
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet1:
    Description: Private Subnet 1
    Type: AWS::EC2::Subnet::Id

  PerspectiveVPCId:
    Description: The id that was assigned to the VPC created in VPC stack
    Type: AWS::EC2::VPC::Id

  SearchLambdaIAMRoleARN:
    Description: Role that lambda function will assume.
    Type: String

  InstanceType:
    Description: The instance type for data nodes
    Type: String
    AllowedValues:
      - t3.small.elasticsearch
      - t3.medium.elasticsearch
      - t2.micro.elasticsearch
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - m5.large.elasticsearch
      - m5.xlarge.elasticsearch
      - m5.2xlarge.elasticsearch
      - m5.4xlarge.elasticsearch
      - m5.12xlarge.elasticsearch
      - m4.large.elasticsearch
      - m4.xlarge.elasticsearch
      - m4.2xlarge.elasticsearch
      - m4.4xlarge.elasticsearch
      - m4.10xlarge.elasticsearch
      - m6g.large.elasticsearch
      - m6g.xlarge.elasticsearch
      - m6g.2xlarge.elasticsearch
      - m6g.4xlarge.elasticsearch
      - m6g.8xlarge.elasticsearch
      - m6g.12xlarge.elasticsearch
      - c5.large.elasticsearch
      - c5.xlarge.elasticsearch
      - c5.2xlarge.elasticsearch
      - c5.4xlarge.elasticsearch
      - c5.9xlarge.elasticsearch
      - c5.19xlarge.elasticsearch
      - c4.large.elasticsearch
      - c4.xlarge.elasticsearch
      - c4.2xlarge.elasticsearch
      - c4.4xlarge.elasticsearch
      - c4.8xlarge.elasticsearch
      - c6g.large.elasticsearch
      - c6g.xlarge.elasticsearch
      - c6g.2xlarge.elasticsearch
      - c6g.4xlarge.elasticsearch
      - c6g.8xlarge.elasticsearch
      - c6g.12xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
      - r5.2xlarge.elasticsearch
      - r5.4xlarge.elasticsearch
      - r5.12xlarge.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - r4.2xlarge.elasticsearch
      - r4.4xlarge.elasticsearch
      - r4.8xlarge.elasticsearch
      - r4.16xlarge.elasticsearch
      - r3.large.elasticsearch
      - r3.xlarge.elasticsearch
      - r3.2xlarge.elasticsearch
      - r3.4xlarge.elasticsearch
      - r3.8xlarge.elasticsearch
      - i3.large.elasticsearch
      - i3.xlarge.elasticsearch
      - i3.2xlarge.elasticsearch
      - i3.4xlarge.elasticsearch
      - i3.8xlarge.elasticsearch
      - i3.16xlarge.elasticsearch

Resources:

  ElasticsearchSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AppName}-ES Security Group
      SecurityGroupEgress:
        - Description: Explicit egress group locking down outbound access HTTP
          CidrIp: !Ref PerspectiveVpcCidr
          IpProtocol: tcp
          ToPort: 80
          FromPort: 80
        - Description: Explicit egress group locking down outbound access for HTTPS
          CidrIp: !Ref PerspectiveVpcCidr
          IpProtocol: tcp
          ToPort: 443
          FromPort: 443
      VpcId:
        Ref: PerspectiveVPCId

  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '7.10'
      ElasticsearchClusterConfig:
        InstanceCount: 2
        InstanceType: !Ref InstanceType
        ZoneAwarenessEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 2
        DedicatedMasterEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      SnapshotOptions:
        AutomatedSnapshotStartHour: 0
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                Ref: SearchLambdaIAMRoleARN
            Action:
              - es:ESHttpGet
              - es:ESHttpPost
              - es:ESHttpPut
              - es:ESHttpDelete
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: 'true'
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ES-Cluster
        - Key: App
          Value: !Ref AppName
        - Key: Version
          Value: '7.10'
      VPCOptions:
        SubnetIds:
          - !Ref PrivateSubnet0
          - !Ref PrivateSubnet1
        SecurityGroupIds:
          - !Ref ElasticsearchSg
    UpdatePolicy:
      EnableVersionUpgrade: true

  ElasticSearchCPUUtilizationTooHighAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster CPU usage above 80%"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "CPUUtilization"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Average"
      Threshold: 80

  ElasticSearchClusterStatusRedAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster status red greater than 1 minute"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "ClusterStatus.red"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Average"
      Threshold: 1

  ElasticSearchClusterStatusYellowAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster status yellow greater than 1 minute"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "ClusterStatus.yellow"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Maximum"
      Threshold: 1

  ElasticSearchClusterJVMMemoryPressureAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster jvm mem pressure too high for more than 1 minute"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "JVMMemoryPressure"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Average"
      Threshold: 85

  ElasticSearchClusterIndexWritesBlockedAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster index writes blocked more than 1 minute"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "ClusterIndexWritesBlocked"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Maximum"
      Threshold: 1

  ElasticSearchClusterAutomatedSnapshotFailureAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: "ES cluster snapshot failed"
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
      TreatMissingData: "missing"
      Dimensions:
        - Name: ClientId
          Value: !Ref "AWS::AccountId"
        - Name: DomainName
          Value: !Ref ElasticsearchDomain
      EvaluationPeriods: 5
      MetricName: "ClusterIndexWritesBlocked"
      Namespace: "AWS/ES"
      Period: 60
      Statistic: "Maximum"
      Threshold: 1

Outputs:

  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint

  ElasticsearchSg:
    Value: !Ref ElasticsearchSg
