env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
    flowVersion: '0.53'
  propWrapperFunctions:
  - forbidExtraProps
  - property: freeze
    object: Object
  - property: myFavoriteWrapper
  linkComponents:
  - Hyperlink
  - name: Link
    linkAttribute: to
rules: {
  no-unused-vars: 1,
  "react/prop-types": 1,
  "react/display-name": 1,
  no-empty-pattern: 1,
  "react/jsx-no-target-blank": 1,
  no-dupe-keys: 1
}
